# SPDX-License-Identifier: AGPL-3.0-only
"""Refuse a commit message that credits a tool instead of a person.

WHY THIS IS A GATE AND NOT A WRITTEN RULE. The prohibition on attribution
trailers already exists in prose, and prose lost the race twice. The agent
definitions that carry it are deployed copies whose freshness check compares a
frontmatter version field and never the body, so an upstream release with a
higher number restores whatever it ships and says nothing. Pinning the upstream
version would stop that and also stop every fix arriving with it, which the
maintainer declined. A rule that an upgrade can overwrite is not a control; a
gate that reads the message at the moment it is written is.

WHAT IT REFUSES, and each entry is narrowed to the shape the footer actually
takes rather than to the words in it:

  * a line that BEGINS with `Generated with`, optionally behind the robot
    emoji. Line-anchored on purpose. The unanchored phrase also matches an
    honest sentence this repository writes often -- "node-specs.json is
    generated by gen_artifacts.py" -- and a gate a contributor can only satisfy
    by deleting a true statement is a defect in the gate.
  * `Claude Code` or `Claude MPM` anywhere. Two-token product names; neither
    has a reading as a person, a method or an English phrase.
  * the robot emoji U+1F916 anywhere.
  * a trailer key beginning `X-AI-`. No standard reserves that prefix and no
    human writes one.
  * a `Co-Authored-By:` trailer whose ADDRESS is machine-shaped. See below.

HOW A HUMAN CO-AUTHOR IS TOLD APART FROM A TOOL CREDIT: BY THE ADDRESS, NEVER
THE DISPLAY NAME. `Co-Authored-By:` is a legitimate git trailer and refusing it
outright would refuse the credit a real collaborator is owed. Matching the
display name instead is the trap: `Claude` is a common French given name, so a
name-matching rule refuses

    Co-authored-by: Claude Dubois <claude.dubois@ens.fr>

and the only way a contributor makes that green is by deleting a person from
the history. The address carries the distinction that the name does not:

  * an agent vendor's own domain -- a person does not hold a mailbox there;
  * GitHub's reserved `[bot]` suffix, which the platform forbids to accounts
    held by people, so its presence is a machine identity by construction;
  * no parsable address at all, which is a malformed trailer no client emits.

`Co-authored-by: Jane Doe <jane@example.com>` passes all three, and so does
every address at a university, a company or a personal domain.

WHERE IT RUNS. Both ends of the same configuration. `.gitlint` names this file
in `extra-path`, so the `commit-msg` hook refuses the commit as it is written,
and the `gitlint` step in `ci.yml` applies the identical rule to every commit
on a pull request and to the squash commit on `main` -- the path a body written
through the merge API takes, which no local hook can see.

A MISSING FILE FAILS LOUD. gitlint resolves `extra-path` before it reads a
message and exits 253 with "Path ... does not exist" when it cannot, so this
rule cannot quietly stop applying by being deleted or moved.
"""

import re

from gitlint.rules import CommitRule, RuleViolation

# Domains from which an agent has been observed to sign a trailer. The list is
# short and it is meant to be: every entry is a vendor's own mail domain, which
# is why a match is conclusive rather than suggestive. It is not the only
# defence -- the product-name and footer patterns below catch the same commits
# through the text that always accompanies the trailer -- so a vendor missing
# here is not an open door.
VENDOR_DOMAINS = (
    "anthropic.com",
    "openai.com",
    "cursor.sh",
    "cursor.com",
    "codeium.com",
    "windsurf.com",
    "cognition.ai",
)

_ADDRESS = re.compile(r"<\s*([^<>@\s]+)@([^<>@\s]+?)\s*>")
_CO_AUTHOR = re.compile(r"^co-authored-by\s*:", re.IGNORECASE)
_X_AI_TRAILER = re.compile(r"^x-ai-[a-z0-9-]*\s*:", re.IGNORECASE)
_GENERATED_FOOTER = re.compile(r"^\W*generated\s+(?:with|by)\b", re.IGNORECASE)
_PRODUCT = re.compile(r"claude\s+(?:code|mpm)", re.IGNORECASE)
_ROBOT = "\U0001f916"


def _is_machine_address(line: str) -> bool:
    """True when the identity on a Co-Authored-By line is not a person's."""
    if "[bot]" in line.lower():
        return True
    found = _ADDRESS.search(line)
    if not found:
        return True
    domain = found.group(2).lower().rstrip(".")
    return any(domain == v or domain.endswith("." + v) for v in VENDOR_DOMAINS)


class NoToolAttribution(CommitRule):
    """Every credit in a commit message names a person."""

    name = "no-tool-attribution"
    id = "UC1"

    def validate(self, commit):
        violations = []
        for number, line in enumerate(commit.message.full.split("\n"), start=1):
            stripped = line.strip()
            reason = None
            if _CO_AUTHOR.match(stripped):
                if _is_machine_address(stripped):
                    reason = (
                        "Co-Authored-By credits a tool, not a person. Remove the "
                        "trailer. A human co-author keeps theirs: the address is "
                        "what is read, so any mailbox outside a vendor domain and "
                        "without GitHub's [bot] suffix is accepted"
                    )
            elif _X_AI_TRAILER.match(stripped):
                reason = "an X-AI- trailer is not written here. Remove the line"
            elif _GENERATED_FOOTER.match(stripped):
                reason = (
                    "a tool-credit footer. Remove the line. The rule is anchored "
                    "to the start of a line, so a sentence saying what generated "
                    "an artifact is untouched"
                )
            if reason is None and _PRODUCT.search(stripped):
                reason = "a tool's product name. Say what changed, not what wrote it"
            if reason is None and _ROBOT in stripped:
                reason = "the robot emoji marks a tool credit. Remove it"
            if reason is not None:
                violations.append(RuleViolation(self.id, reason, line, number))
        return violations
